# Generated by Django 4.0.1 on 2022-04-14 16:38

from django.db import migrations, models
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=tkinter.tix.Tree, null=True, upload_to=''),
        ),
    ]
