# Generated by Django 4.0.5 on 2022-06-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
